### ISSUE TITLE
!top ranks not updating until player disconnect from the server

### ISSUE THREAD

**Issue by dialupa** [K4ryuu/K4-System#17]
Hello just wanted to firstly say amazing job I love the plugin. I was wondering if  it's possible to make it so the !top command updated more frequently, it seems it's only updating when players disconnect from the server at the moment

**Comment by K4ryuu** [comment]
Hello!

The extension is designed to operate efficiently, especially during high player counts, which prevents excessive MySQL queries and task executions by refreshing only at specific events.

I’m considering an enhancement to include a full refresh package when checking toplists for all online players, akin to how individual player information is updated when they check their own info.

This change would improve the system rather than address a bug.

**Comment by K4ryuu** [comment]
Greetings,
I have implemented save for all players upon the top list is getting opened. 
I am going to upload the new version, whenever all the urgent issues are closed.

Thank you for the request, and for using GitHub issues!

Best Regards,
K4ryuu
