### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by blu133721** [K4ryuu/K4-System#18]
**Describe the bug**
Hello,

I am running your latest K4-System with CSS Version API 50.

I have found a very weird bug, when planting the bomb on B site with atleast two players in the server connected, the server just crashes when the bomb is at 0 seconds to explode (I have tested it only on B site, but I think it's working also in any other site.)

**To Reproduce**
1. Disable all meta plugins other than CSharp and K4-System
2. Get two players in the server and plant the bomb (preferably) at B Site
3. Wait for the bomb to reach 0 seconds of exploding and watch the server crash.

**Expected behavior**
The expected behavior is that the server shouldn't crash and just give the points for losing/detonating the bomb.

**Comment by blu133721** [comment]
Also, the server crash is looking something like this: 
![image](https://github.com/K4ryuu/K4-System/assets/73272097/6aa696c4-f808-4ec9-8645-7c82931c1ba4)

**Comment by K4ryuu** [comment]
Greetings,
However your issue is perfectly written (except the title), which I really appreciate, I was unable to reproduce the bug. Tried to plant and defuse / not defuse several times, but no crashes. 

However I'm currently using a patched version, which MAY already contain the bug fix. 

I will close now the issue, since I was unable to repro, but you can reopen it again, if the problem appears again and then we test it further.

Best Regards and much appreciation for the quality issue,
K4ryuu
