### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GravityUA** [K4ryuu/K4-System#20]
I recorded a video for you of how I get a server crash https://youtu.be/8Us7u071Wvc

**Comment by K4ryuu** [comment]
Hello,
This is the third duplicate of this report, and if you check those, I have already answered. There is a highly upgraded version, which I'm working on currently a few hour ago, so maybe that fixed it.

If not, you can enable debug mode in the new version and help me debug it, since with my current version I'm unable to reproduce the bug. Maybe because it is already fixed.

Best Regards,
K4ryuu

**Comment by GravityUA** [comment]
![Screenshot_1](https://github.com/K4ryuu/K4-System/assets/148160078/ff0097c5-4fad-4df8-833a-35caad3df16e)
[f1fae786-9e8b-41cf-151b4ebf-c0b0848e.dmp](https://github.com/K4ryuu/K4-System/files/13384484/f1fae786-9e8b-41cf-151b4ebf-c0b0848e.dmp)
[f1fae786-9e8b-41cf-151b4ebf-c0b0848e.dmp.txt](https://github.com/K4ryuu/K4-System/files/13384485/f1fae786-9e8b-41cf-151b4ebf-c0b0848e.dmp.txt)

**Comment by GravityUA** [comment]
![Screenshot_2](https://github.com/K4ryuu/K4-System/assets/148160078/a223b247-edf7-4ff6-94f0-dd2fde4f6a81)
that's all it's worth

**Comment by GravityUA** [comment]
I FOUND OUT WHY THE SERVER FALLED THE SERVER

THE FAULT WAS THE ACCELERATOR FROM PHOENIX
