### ISSUE TITLE
[BUG] Not record headshots

### ISSUE THREAD

**Issue by skaen** [K4ryuu/K4-System#23]
does not record headshots
![image](https://github.com/K4ryuu/K4-System/assets/17942495/a418ac52-b9b7-46ac-af90-442556b3d8b2)

**Comment by skaen** [comment]
and round_win & round_lose & grenades
![image](https://github.com/K4ryuu/K4-System/assets/17942495/b81ad3f8-02b7-401f-b28d-77f568c734c6)

**Comment by freakexeuLow** [comment]
> and round_win & round_lose & grenades ![image](https://user-images.githubusercontent.com/17942495/283850445-b81ad3f8-02b7-401f-b28d-77f568c734c6.png)

mhh the round_win or round_lose works for me fine
![51d0567823ecc2cafd183e995f1004c8](https://github.com/K4ryuu/K4-System/assets/32603929/205e03c0-7788-4538-b1df-2bd5d16ef944)

**Comment by K4ryuu** [comment]
Headshot is being fixed in the upcoming release, but with round end and grenades I didn't find any problems.
Possibly the next version will be good for all of them.

I keep the ticket open and I ask you gently to close it if the problem is solved or give a feedback if it's not.

Thank you very much!

**Comment by skaen** [comment]
Headshots fixed
