### ISSUE TITLE
[REQ] Point exchange system

### ISSUE THREAD

**Issue by Magic8Ballin** [K4ryuu/K4-System#57]
Would you consider adding a points exchange system?

Similar to GameME or HLStatsX. When a player kills someone, a calculation is done to determine how many points the player will receive for the kill.

When a player's stats profile is first created, they are assigned 1000 points. As players get kills, they will receive more or less points determined by the victim's points in relation to their own.

If the player they killed has higher points, they are rewarded more points. If the player they called has fewer points, they receive fewer points. 

Here's an example of the formula that GameME uses.

Killer Points = Killer Points + (Victim Points / Killer Points) × Weapon Modifier × 5

Victim Points = Victim Points - (Victim Points / Killer Points) × Weapon Modifier × 5

**Comment by K4ryuu** [comment]
Greetings,
Great idea. I will add this for sure. However what weapon modifiers could there be? Also why is there a "x 5" at the end?

**Comment by NotJustin** [comment]
> What weapon modifiers could there be?

If you want to follow the same as what gameME did, most of these options are configurable by the server operator.

The list of weapons are configurable (in case CS2 adds more weapons, or if a mod allows custom weapons?), and each weapon has its own configurable modifier.

> why is there a "x 5" at the end?

The "x 5" serves as a modifier to increase the points exchanged to "5" instead of "1".
example: Two equal points players kill eachother with a weapon that has a 1.0 modifier.
Points gained = 1.0 * 1.0 * 5.0 = 5

I do not know exactly why they chose 5, but I think it is useful to have some configurable number here. This allows the server operator to multiply the points exchanged across all weapons, if they just want to have a point system that has smaller or larger numbers.

Additional info:
gameME default sets new players to 1000 points. I think this should also be configurable, but, if the server operator attempts to change this value, maybe warn/advise them that they should reset their stats/database. It would be weird if players first started at 1000, play for awhile, and then suddenly new players are starting at 5000 points while the old players are still only at smaller numbers.

On the other hand, if you do not wish to make things configurable but would like to know the numbers gameME uses anyway, the gameME website lists all servers that use their service here: https://www.gameme.com/en/gameservers and I found a server that I think has not changed their default values here: https://stats.cs-meat.com/help
(section titled "3. What are all the weapon points modifiers?")
